{% set name = "mbovpan" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: "https://github.com/salvadorlab/mbovpan.git"

build:
  always_include_files:
    -	./mbovpan.nf
		-	./build.sh
		-	./envs
		-	./envs/prokka.yaml
		-	./envs/vcflib.yaml~
		-	./envs/gene_prab.yaml
		-	./envs/consensus.yaml
		-	./envs/samtools.yaml
		-	./envs/megahit.yaml
		-	./envs/multiqc.yaml
		-	./envs/raven.yaml
		-	./envs/roary.yaml
		-	./envs/freebayes.yaml
		-	./envs/mbovpan.yaml
		-	./envs/statistics.yaml
		-	./envs/tbprofile.yaml
		-	./envs/quast.yaml
		-	./envs/vcflib.yaml
		-	./envs/longread.yaml
		-	./envs/iqtree.yaml
		-	./envs/picard.yaml
		-	./envs/scoary.yaml
		-	./dev_nf_scripts
		-	./dev_nf_scripts/spades_assem.nf
		-	./dev_nf_scripts/megahit_assem.nf
		-	./dev_nf_scripts/spotyping.nf
		-	./dev_nf_scripts/calling_snps.nf
		-	./dev_nf_scripts/bowtie_call.nf
		-	./dev_nf_scripts/smalt_call.nf
		-	./dev_nf_scripts/gene_prab.nf
		-	./dev_nf_scripts/accessory_pca.nf
		-	./dev_nf_scripts/tbprofiler.nf
		-	./dev_nf_scripts/abyss_assem.nf
		-	./dev_nf_scripts/minimap_call.nf
		-	./ref
		-	./ref/mbov_bowtie_index.rev.1.bt2
		-	./ref/mbov_bowtie_index.4.bt2
		-	./ref/mbovAF212297_reference.fasta.pac
		-	./ref/mbov_bowtie_index.rev.2.bt2
		-	./ref/mbovAF212297_reference.fasta.sa
		-	./ref/mbov_reference.fasta
		-	./ref/mbovAF212297_reference.fasta.bwt
		-	./ref/mbov_bowtie_index.2.bt2
		-	./ref/mbovAF212297_reference.fasta.dict
		-	./ref/pe_ppe_regions.gff3
		-	./ref/mbovAF212297_reference.fasta.ann
		-	./ref/mbovAF212297_reference.fasta
		-	./ref/mbovAF212297_reference.fasta.fai
		-	./ref/spacer.fasta
		-	./ref/mbovAF212297_annotation.gb
		-	./ref/mbovAF212297_reference.fasta.amb
		-	./ref/mbov_bowtie_index.3.bt2
		-	./ref/mbov_bowtie_index.1.bt2
		-	./.DS_Store
		-	./bld.bat
		-	./README.md
		-	./mbovpan
		-	./meta.yaml
		-	./.vs
		-	./.vs/VSWorkspaceState.json
		-	./.vs/ProjectSettings.json
		-	./.vs/slnx.sqlite
		-	./.vs/mbovpan
		-	./.vs/mbovpan/v16
		-	./.vs/mbovpan/v16/Browse.VC.db
		-	./.vs/mbovpan/v16/.suo
		-	./scripts
		-	./scripts/accessory_pca.R
		-	./scripts/SpoTyping_copy.py
		-	./scripts/install_mbovpan.sh
		-	./scripts/statistics.py
		-	./scripts/pangenome_curve.R
		-	./scripts/gene_prab.R
		-	./scripts/mbov_virulence.py
		-	./scripts/SpoTyping
		-	./scripts/SpoTyping/Update-history.md
		-	./scripts/SpoTyping/SpoTyping-README-md.pdf
		-	./scripts/SpoTyping/SpoTyping.py
		-	./scripts/SpoTyping/ref
		-	./scripts/SpoTyping/ref/spacer.fasta
		-	./scripts/SpoTyping/README.md
		-	./scripts/SpoTyping/SpoTyping_plot.r


requirements:
  host:
    - nextflow=22.10.6
  run:
    - nextflow=22.10.6

test:
  source_files:
    - mbovpan.nf
  commands:
    - ls; nextflow run mbovpan.nf --help

about:
  home: "https://github.com/salvadorlab/mbovpan.git"
  summary: "nextflow pipeline for Mycobacterium bovis pangenome analysis."


extra:
  recipe-maintainers:
    - noahlegall
